### ISSUE TITLE
Sometimes it does not work .

### ISSUE THREAD

**Issue by Hasan36arnob** [codebucks27/AI-Powered-Twitter-Bio-Generator#1]
Yesterday when I first tried it , it was working fine. Today it just generated output one or two time but most of the time it did not generate any output.  
![image](https://github.com/user-attachments/assets/0365429b-7b03-4a5f-94f0-ad7567ec4504)

**Comment by codebucks27** [comment]
I'd suggest you to try new models. Checkout the latest supported models from here: https://console.groq.com/docs/models.
Since we are using tool call use this model for better response: **llama3-groq-70b-8192-tool-use-preview**
